### ISSUE TITLE
Error in IOS Simulator

### ISSUE THREAD

**Issue by ChiragBhalara07** [vaskort/react-native#1]
When i am going to run `react-native run-ios` then after app install successfully in simulator but it's giving error.

undefined is not an object (evaluating '_reactNativeAndroidLocationServicesDialogBox2.default.checkLocationServicesIsEnabled')

**Comment by vaskort** [comment]
hey @ChiragBhalara07 thanks for opening an issue. You did run `npm install` first right?

**Comment by vaskort** [comment]
Please pull the branch `clone-ready` and everything should work
