### ISSUE TITLE
Error in Android Simulator or android tab

### ISSUE THREAD

**Issue by Toutlemond** [vaskort/react-native#2]
Hi! 
I clone your app and run npm install. 
When i am going to run react-native run-android then after app build successfully, it writes 
BUILD SUCCESSFUL

Total time: 1 mins 22.396 secs
Starting the app on emulator-5554 (C: \ Users \ user \ AppData \ Local \ Android \ Sdk / platform-tools / adb -s emulator-5554 shell am start -n com.locationsaverr / .MainActivity) ...
Starting: Intent {cmp = com.locationsaverr / .MainActivity}
Error type 3
Error: Activity class {com.locationsaverr / com.locationsaverr.MainActivity} does not exist.

I tried everything that Google gives out on this error.
Change the name of the application in AndroidManifest.xml, version of Api on the emulator.
Nothing helps! 
![photo_2017-06-06_15-40-39](https://cloud.githubusercontent.com/assets/28943313/26825425/67d2891c-4ace-11e7-8900-7ea807d494e0.jpg)

**Comment by vaskort** [comment]
Hey @Toutlemond, the package name is `com.locationsaver` not `com.locationsaverr`, this is the issue but no idea how this happened, but this is the issue for sure. 

Can you start in a clean folder again from the beginning and let me know.

**Comment by Toutlemond** [comment]
Ups ,I apologize that I already applied some tips from stackoverflow.com.
With the original name the same error.
![photo_2017-06-06_15-56-11](https://cloud.githubusercontent.com/assets/28943313/26825956/74015da6-4ad0-11e7-944d-6c2d7383edba.jpg)

 this happened cause i change name in androidManifest- just for test
Ok i can start in clean folder

**Comment by vaskort** [comment]
Yes please @Toutlemond, and let me know :) I will investigate later anyway.

**Comment by Toutlemond** [comment]
I did it.
The same error.
![1](https://cloud.githubusercontent.com/assets/28943313/26826733/8cd37bfe-4ad3-11e7-882e-68d649a02025.jpg)

After install i run react-native run-android

![2](https://cloud.githubusercontent.com/assets/28943313/26826762/a71ecce8-4ad3-11e7-8bb4-d231406527c3.jpg)
And get same error
![3](https://cloud.githubusercontent.com/assets/28943313/26826782/b95c1780-4ad3-11e7-8867-a5d7b38da057.jpg)

**Comment by vaskort** [comment]
@Toutlemond This seems relevant, can you try the solution? https://stackoverflow.com/questions/35131769/error-type-3-activity-class-com-awesome-project-com-awesome-project-mainactiv

**Comment by Toutlemond** [comment]
You mean - do the names match?
In the build.gradle, 
MainActivity.java,
MainApplication.java,
AndroidManifest.xml
? 
build.gradle, dose not have  "defaultConfig {}" section
the other files match - com.locationsaver

**Comment by vaskort** [comment]
It's ok that does not have it can you add it please? 

So it would be like this: 

```
android {
    compileSdkVersion 23
    buildToolsVersion "25"

    defaultConfig {
        applicationId "com.locationsaver"
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 2
        versionName "2.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
etc
```

**Comment by Toutlemond** [comment]
hmmm I'm not very strong in Gradle, so I did something like this - 
// Top-level build file where you can add configuration options common to all sub-projects/modules.
android {
    compileSdkVersion 23
    buildToolsVersion "25"

    defaultConfig {
        applicationId "com.locationsaver"
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 2
        versionName "2.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
}

and i have another error - 
![photo_2017-06-06_17-01-55](https://cloud.githubusercontent.com/assets/28943313/26828174/a7323782-4ad9-11e7-8135-2f2e1153d2fc.jpg)

**Comment by vaskort** [comment]
@Toutlemond Something is messed up with my gitignore file give me one or two days and I'll fix the issue. Will let you know. thanks for opening the issue :)

**Comment by Toutlemond** [comment]
Thank you!
I want to study React-native and work with maps on your application.

**Comment by vaskort** [comment]
hey @Toutlemond can you checkout the branch `issue-2-gitignore-fix` ? I won't merge it right now as I want to test it first, it seems that my .gitignore was too strict and some files were missing from master. Please let me know :)

**Comment by Toutlemond** [comment]
Thank you!
I tried. 
Created a new folder, copied a new branch there. 
After that -  npm Instal and react-native run android.
But now there are errors at the moment of the application build.
![photo_2017-06-08_16-00-21](https://user-images.githubusercontent.com/28943313/26925487-6a50f214-4c63-11e7-9e15-b5a46c55085e.jpg)

**Comment by vaskort** [comment]
@Toutlemond Hey mate, it seems that it will take some more time and can't fix it today. Maybe I have to have two separate branches one for me when releasing, with my release key and one for cloning purposes. I will investigate tomorrow morning when I'll be slightly more flexible. Thanks for your patience :)

**Comment by vaskort** [comment]
@Toutlemond Hello, can you pull again my changes of `issue-2-gitignore-fix` branch please and let me know?

**Comment by vaskort** [comment]
@Toutlemond Did you had the chance to try it?

**Comment by Toutlemond** [comment]
Good afternoon! I apologize for not responding for a long time.
I took the update and launch it.
At first glance, the problem remained - 
![1](https://user-images.githubusercontent.com/28943313/27320047-d6ad6444-55ad-11e7-8515-ad9430006df2.jpg)
But the application appeared on the phone.
And if you run it -  all works
![2](https://user-images.githubusercontent.com/28943313/27320117-1ea89eda-55ae-11e7-8bdc-4019f508f4df.jpg)
![3](https://user-images.githubusercontent.com/28943313/27320116-1ea6fff8-55ae-11e7-838a-6600ac541f45.jpg)

**Comment by Toutlemond** [comment]
Thanks for your application.
It helps me to better understand React Native and google maps!

**Comment by vaskort** [comment]
@Toutlemond I'm so glad it helps you :)
